### ISSUE TITLE
异常返回的错误码是0

### ISSUE THREAD

**Issue by Reathin** [wang2793312458/EZOpenSDK#1]

**Comment by wang2793312458** [comment]
留个联系方式吧，重新发你一份

**Comment by wang2793312458** [comment]
https://open.ys7.com/view/sdk/sdk.html#type=APP
下载SDK，里面有demo，如遇开发问题
，请参考官方文档

**Comment by wang2793312458** [comment]
https://open.ys7.com/doc/zh/book/index/android-errorcode.html
